f = open("data",encoding = "utf-8", mode= "r")
frow=f.readline()
frow=frow.split(" ")
len1=len(frow)
print(frow[len1-1])
secrow=f.readline()
secrow=secrow.split(" ")
len2=len(secrow)
print(secrow[len2-1])